#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.

   The implementation is messy (issue #350): on Windows, with _MSC_VER,
   we have to define Py_LIMITED_API even before including pyconfig.h.
   In that case, we guess what pyconfig.h will do to the macros above,
   and check our guess after the #include.

   Note that on Windows, with CPython 3.x, you need >= 3.5 and virtualenv
   version >= 16.0.0.  With older versions of either, you don't get a
   copy of PYTHON3.DLL in the virtualenv.  We can't check the version of
   CPython *before* we even include pyconfig.h.  ffi.set_source() puts
   a ``#define _CFFI_NO_LIMITED_API'' at the start of this file if it is
   running on Windows < 3.5, as an attempt at fixing it, but that's
   arguably wrong because it may not be the target version of Python.
   Still better than nothing I guess.  As another workaround, you can
   remove the definition of Py_LIMITED_API here.

   See also 'py_limited_api' in cffi/setuptools_ext.py.
*/
#if !defined(_CFFI_USE_EMBEDDING) && !defined(Py_LIMITED_API)
#  ifdef _MSC_VER
#    if !defined(_DEBUG) && !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#    include <pyconfig.h>
     /* sanity-check: Py_LIMITED_API will cause crashes if any of these
        are also defined.  Normally, the Python file PC/pyconfig.h does not
        cause any of these to be defined, with the exception that _DEBUG
        causes Py_DEBUG.  Double-check that. */
#    ifdef Py_LIMITED_API
#      if defined(Py_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_DEBUG, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_TRACE_REFS)
#        error "pyconfig.h unexpectedly defines Py_TRACE_REFS, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_REF_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_REF_DEBUG, but Py_LIMITED_API is set"
#      endif
#    endif
#  else
#    include <pyconfig.h>
#    if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>

/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47
#define _CFFI_PRIM_FLOATCOMPLEX 48
#define _CFFI_PRIM_DOUBLECOMPLEX 49
#define _CFFI_PRIM_CHAR16       50
#define _CFFI_PRIM_CHAR32       51

#define _CFFI__NUM_PRIM         52
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#if PY_MAJOR_VERSION >= 3
# define PyInt_FromLong PyLong_FromLong
#endif

#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyInt_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong
#define _cffi_from_c__Bool PyBool_FromLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyInt_FromLong((long)x) :                                    \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyInt_FromLong((long)x) :                                    \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((_cffi_wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(_cffi_wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _cffi_to_c_wchar3216_t                                           \
    ((int(*)(PyObject *))_cffi_exports[26])
#define _cffi_from_c_wchar3216_t                                         \
    ((PyObject *(*)(int))_cffi_exports[27])
#define _CFFI_NUM_EXPORTS 28

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}


#ifdef HAVE_WCHAR_H
typedef wchar_t _cffi_wchar_t;
#else
typedef uint16_t _cffi_wchar_t;   /* same random pick as _cffi_backend.c */
#endif

_CFFI_UNUSED_FN static uint16_t _cffi_to_c_char16_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return (uint16_t)_cffi_to_c_wchar_t(o);
    else
        return (uint16_t)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char16_t(uint16_t x)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

_CFFI_UNUSED_FN static int _cffi_to_c_char32_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return (int)_cffi_to_c_wchar_t(o);
    else
        return (int)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char32_t(unsigned int x)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

union _cffi_union_alignment_u {
    unsigned char m_char;
    unsigned short m_short;
    unsigned int m_int;
    unsigned long m_long;
    unsigned long long m_longlong;
    float m_float;
    double m_double;
    long double m_longdouble;
};

struct _cffi_freeme_s {
    struct _cffi_freeme_s *next;
    union _cffi_union_alignment_u alignment;
};

_CFFI_UNUSED_FN static int
_cffi_convert_array_argument(struct _cffi_ctypedescr *ctptr, PyObject *arg,
                             char **output_data, Py_ssize_t datasize,
                             struct _cffi_freeme_s **freeme)
{
    char *p;
    if (datasize < 0)
        return -1;

    p = *output_data;
    if (p == NULL) {
        struct _cffi_freeme_s *fp = (struct _cffi_freeme_s *)PyObject_Malloc(
            offsetof(struct _cffi_freeme_s, alignment) + (size_t)datasize);
        if (fp == NULL)
            return -1;
        fp->next = *freeme;
        *freeme = fp;
        p = *output_data = (char *)&fp->alignment;
    }
    memset((void *)p, 0, (size_t)datasize);
    return _cffi_convert_array_from_object(p, ctptr, arg);
}

_CFFI_UNUSED_FN static void
_cffi_free_array_arguments(struct _cffi_freeme_s *freeme)
{
    do {
        void *p = (void *)freeme;
        freeme = freeme->next;
        PyObject_Free(p);
    } while (freeme != NULL);
}

/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/


struct statfs {
    __fsword_t f_type;
    __fsword_t f_bsize;
    __fsblkcnt_t f_blocks;
    __fsblkcnt_t f_bfree;
    __fsblkcnt_t f_bavail;
    __fsfilcnt_t f_files;
    __fsfilcnt_t f_ffree;
    __fsid_t f_fsid;
    __fsword_t f_namelen;
    __fsword_t f_frsize;
    __fsword_t f_flags;
    __fsword_t f_spare[4];
};

extern int statfs(const char* path, struct statfs* stat);
#define ADFS_SUPER_MAGIC 0xadf5
#define AFFS_SUPER_MAGIC 0xadff
#define AFS_SUPER_MAGIC 0x5346414F
#define AUTOFS_SUPER_MAGIC 0x0187
#define CODA_SUPER_MAGIC 0x73757245
#define CRAMFS_MAGIC 0x28cd3d45
#define CRAMFS_MAGIC_WEND 0x453dcd28
#define DEBUGFS_MAGIC 0x64626720
#define SECURITYFS_MAGIC 0x73636673
#define SELINUX_MAGIC 0xf97cff8c
#define SMACK_MAGIC 0x43415d53
#define RAMFS_MAGIC 0x858458f6
#define TMPFS_MAGIC 0x01021994
#define HUGETLBFS_MAGIC 0x958458f6
#define SQUASHFS_MAGIC 0x73717368
#define ECRYPTFS_SUPER_MAGIC 0xf15f
#define EFS_SUPER_MAGIC 0x414A53
#define EROFS_SUPER_MAGIC_V1 0xE0F5E1E2
#define EXT2_SUPER_MAGIC 0xEF53
#define EXT3_SUPER_MAGIC 0xEF53
#define XENFS_SUPER_MAGIC 0xabba1974
#define EXT4_SUPER_MAGIC 0xEF53
#define BTRFS_SUPER_MAGIC 0x9123683E
#define NILFS_SUPER_MAGIC 0x3434
#define F2FS_SUPER_MAGIC 0xF2F52010
#define HPFS_SUPER_MAGIC 0xf995e849
#define ISOFS_SUPER_MAGIC 0x9660
#define JFFS2_SUPER_MAGIC 0x72b6
#define XFS_SUPER_MAGIC 0x58465342
#define PSTOREFS_MAGIC 0x6165676C
#define EFIVARFS_MAGIC 0xde5e81e4
#define HOSTFS_SUPER_MAGIC 0x00c0ffee
#define OVERLAYFS_SUPER_MAGIC 0x794c7630
#define MINIX_SUPER_MAGIC 0x137F
#define MINIX_SUPER_MAGIC2 0x138F
#define MINIX2_SUPER_MAGIC 0x2468
#define MINIX2_SUPER_MAGIC2 0x2478
#define MINIX3_SUPER_MAGIC 0x4d5a
#define MSDOS_SUPER_MAGIC 0x4d44
#define NCP_SUPER_MAGIC 0x564c
#define NFS_SUPER_MAGIC 0x6969
#define OCFS2_SUPER_MAGIC 0x7461636f
#define OPENPROM_SUPER_MAGIC 0x9fa1
#define QNX4_SUPER_MAGIC 0x002f
#define QNX6_SUPER_MAGIC 0x68191122
#define AFS_FS_MAGIC 0x6B414653
#define REISERFS_SUPER_MAGIC 0x52654973
#define SMB_SUPER_MAGIC 0x517B
#define CGROUP_SUPER_MAGIC 0x27e0eb
#define CGROUP2_SUPER_MAGIC 0x63677270
#define RDTGROUP_SUPER_MAGIC 0x7655821
#define STACK_END_MAGIC 0x57AC6E9D
#define TRACEFS_MAGIC 0x74726163
#define V9FS_MAGIC 0x01021997
#define BDEVFS_MAGIC 0x62646576
#define DAXFS_MAGIC 0x64646178
#define BINFMTFS_MAGIC 0x42494e4d
#define DEVPTS_SUPER_MAGIC 0x1cd1
#define BINDERFS_SUPER_MAGIC 0x6c6f6f70
#define FUTEXFS_SUPER_MAGIC 0xBAD1DEA
#define PIPEFS_MAGIC 0x50495045
#define PROC_SUPER_MAGIC 0x9fa0
#define SOCKFS_MAGIC 0x534F434B
#define SYSFS_MAGIC 0x62656572
#define USBDEVICE_SUPER_MAGIC 0x9fa2
#define MTD_INODE_FS_MAGIC 0x11307854
#define ANON_INODE_FS_MAGIC 0x09041934
#define BTRFS_TEST_MAGIC 0x73727279
#define NSFS_MAGIC 0x6e736673
#define BPF_FS_MAGIC 0xcafe4a11
#define AAFS_MAGIC 0x5a3c69f0
#define ZONEFS_MAGIC 0x5a4f4653
#define UDF_SUPER_MAGIC 0x15013346
#define BALLOON_KVM_MAGIC 0x13661366
#define ZSMALLOC_MAGIC 0x58295829
#define DMA_BUF_MAGIC 0x444d4142
#define DEVMEM_MAGIC 0x454d444d
#define Z3FOLD_MAGIC 0x33
#define PPC_CMM_MAGIC 0xc7571590
#define SHIFTFS_MAGIC 0x6a656a62


/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 6), // int()(char const *, struct statfs *)
/*  1 */ _CFFI_OP(_CFFI_OP_POINTER, 5), // char const *
/*  2 */ _CFFI_OP(_CFFI_OP_POINTER, 12), // struct statfs *
/*  3 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  4 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 0), // __fsid_t
/*  5 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 2), // char
/*  6 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7), // int
/*  7 */ _CFFI_OP(_CFFI_OP_ARRAY, 6), // int[2]
/*  8 */ (_cffi_opcode_t)(2),
/*  9 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 9), // long
/* 10 */ _CFFI_OP(_CFFI_OP_ARRAY, 9), // long[4]
/* 11 */ (_cffi_opcode_t)(4),
/* 12 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 1), // struct statfs
/* 13 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 10), // unsigned long
};

_CFFI_UNUSED_FN
static void _cffi_checkfld_typedef___fsid_t(__fsid_t *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { int(*tmp)[2] = &p->__val; (void)tmp; }
}
struct _cffi_align_typedef___fsid_t { char x; __fsid_t y; };

static int _cffi_d_statfs(char const * x0, struct statfs * x1)
{
  return statfs(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_statfs(PyObject *self, PyObject *args)
{
  char const * x0;
  struct statfs * x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  int result;
  PyObject *pyresult;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "statfs", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (char const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(2), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (struct statfs *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(2), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = statfs(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  pyresult = _cffi_from_c_int(result, int);
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  return pyresult;
}
#else
#  define _cffi_f_statfs _cffi_d_statfs
#endif

static int _cffi_const_AAFS_MAGIC(unsigned long long *o)
{
  int n = (AAFS_MAGIC) <= 0;
  *o = (unsigned long long)((AAFS_MAGIC) | 0);  /* check that AAFS_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 1513908720U))
    n |= 2;
  return n;
}

static int _cffi_const_ADFS_SUPER_MAGIC(unsigned long long *o)
{
  int n = (ADFS_SUPER_MAGIC) <= 0;
  *o = (unsigned long long)((ADFS_SUPER_MAGIC) | 0);  /* check that ADFS_SUPER_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 44533U))
    n |= 2;
  return n;
}

static int _cffi_const_AFFS_SUPER_MAGIC(unsigned long long *o)
{
  int n = (AFFS_SUPER_MAGIC) <= 0;
  *o = (unsigned long long)((AFFS_SUPER_MAGIC) | 0);  /* check that AFFS_SUPER_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 44543U))
    n |= 2;
  return n;
}

static int _cffi_const_AFS_FS_MAGIC(unsigned long long *o)
{
  int n = (AFS_FS_MAGIC) <= 0;
  *o = (unsigned long long)((AFS_FS_MAGIC) | 0);  /* check that AFS_FS_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 1799439955U))
    n |= 2;
  return n;
}

static int _cffi_const_AFS_SUPER_MAGIC(unsigned long long *o)
{
  int n = (AFS_SUPER_MAGIC) <= 0;
  *o = (unsigned long long)((AFS_SUPER_MAGIC) | 0);  /* check that AFS_SUPER_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 1397113167U))
    n |= 2;
  return n;
}

static int _cffi_const_ANON_INODE_FS_MAGIC(unsigned long long *o)
{
  int n = (ANON_INODE_FS_MAGIC) <= 0;
  *o = (unsigned long long)((ANON_INODE_FS_MAGIC) | 0);  /* check that ANON_INODE_FS_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 151263540U))
    n |= 2;
  return n;
}

static int _cffi_const_AUTOFS_SUPER_MAGIC(unsigned long long *o)
{
  int n = (AUTOFS_SUPER_MAGIC) <= 0;
  *o = (unsigned long long)((AUTOFS_SUPER_MAGIC) | 0);  /* check that AUTOFS_SUPER_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 391U))
    n |= 2;
  return n;
}

static int _cffi_const_BALLOON_KVM_MAGIC(unsigned long long *o)
{
  int n = (BALLOON_KVM_MAGIC) <= 0;
  *o = (unsigned long long)((BALLOON_KVM_MAGIC) | 0);  /* check that BALLOON_KVM_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 325456742U))
    n |= 2;
  return n;
}

static int _cffi_const_BDEVFS_MAGIC(unsigned long long *o)
{
  int n = (BDEVFS_MAGIC) <= 0;
  *o = (unsigned long long)((BDEVFS_MAGIC) | 0);  /* check that BDEVFS_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 1650746742U))
    n |= 2;
  return n;
}

static int _cffi_const_BINDERFS_SUPER_MAGIC(unsigned long long *o)
{
  int n = (BINDERFS_SUPER_MAGIC) <= 0;
  *o = (unsigned long long)((BINDERFS_SUPER_MAGIC) | 0);  /* check that BINDERFS_SUPER_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 1819242352U))
    n |= 2;
  return n;
}

static int _cffi_const_BINFMTFS_MAGIC(unsigned long long *o)
{
  int n = (BINFMTFS_MAGIC) <= 0;
  *o = (unsigned long long)((BINFMTFS_MAGIC) | 0);  /* check that BINFMTFS_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 1112100429U))
    n |= 2;
  return n;
}

static int _cffi_const_BPF_FS_MAGIC(unsigned long long *o)
{
  int n = (BPF_FS_MAGIC) <= 0;
  *o = (unsigned long long)((BPF_FS_MAGIC) | 0);  /* check that BPF_FS_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 3405662737U))
    n |= 2;
  return n;
}

static int _cffi_const_BTRFS_SUPER_MAGIC(unsigned long long *o)
{
  int n = (BTRFS_SUPER_MAGIC) <= 0;
  *o = (unsigned long long)((BTRFS_SUPER_MAGIC) | 0);  /* check that BTRFS_SUPER_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 2435016766U))
    n |= 2;
  return n;
}

static int _cffi_const_BTRFS_TEST_MAGIC(unsigned long long *o)
{
  int n = (BTRFS_TEST_MAGIC) <= 0;
  *o = (unsigned long long)((BTRFS_TEST_MAGIC) | 0);  /* check that BTRFS_TEST_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 1936880249U))
    n |= 2;
  return n;
}

static int _cffi_const_CGROUP2_SUPER_MAGIC(unsigned long long *o)
{
  int n = (CGROUP2_SUPER_MAGIC) <= 0;
  *o = (unsigned long long)((CGROUP2_SUPER_MAGIC) | 0);  /* check that CGROUP2_SUPER_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 1667723888U))
    n |= 2;
  return n;
}

static int _cffi_const_CGROUP_SUPER_MAGIC(unsigned long long *o)
{
  int n = (CGROUP_SUPER_MAGIC) <= 0;
  *o = (unsigned long long)((CGROUP_SUPER_MAGIC) | 0);  /* check that CGROUP_SUPER_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 2613483U))
    n |= 2;
  return n;
}

static int _cffi_const_CODA_SUPER_MAGIC(unsigned long long *o)
{
  int n = (CODA_SUPER_MAGIC) <= 0;
  *o = (unsigned long long)((CODA_SUPER_MAGIC) | 0);  /* check that CODA_SUPER_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 1937076805U))
    n |= 2;
  return n;
}

static int _cffi_const_CRAMFS_MAGIC(unsigned long long *o)
{
  int n = (CRAMFS_MAGIC) <= 0;
  *o = (unsigned long long)((CRAMFS_MAGIC) | 0);  /* check that CRAMFS_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 684539205U))
    n |= 2;
  return n;
}

static int _cffi_const_CRAMFS_MAGIC_WEND(unsigned long long *o)
{
  int n = (CRAMFS_MAGIC_WEND) <= 0;
  *o = (unsigned long long)((CRAMFS_MAGIC_WEND) | 0);  /* check that CRAMFS_MAGIC_WEND is an integer */
  if (!_cffi_check_int(*o, n, 1161678120U))
    n |= 2;
  return n;
}

static int _cffi_const_DAXFS_MAGIC(unsigned long long *o)
{
  int n = (DAXFS_MAGIC) <= 0;
  *o = (unsigned long long)((DAXFS_MAGIC) | 0);  /* check that DAXFS_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 1684300152U))
    n |= 2;
  return n;
}

static int _cffi_const_DEBUGFS_MAGIC(unsigned long long *o)
{
  int n = (DEBUGFS_MAGIC) <= 0;
  *o = (unsigned long long)((DEBUGFS_MAGIC) | 0);  /* check that DEBUGFS_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 1684170528U))
    n |= 2;
  return n;
}

static int _cffi_const_DEVMEM_MAGIC(unsigned long long *o)
{
  int n = (DEVMEM_MAGIC) <= 0;
  *o = (unsigned long long)((DEVMEM_MAGIC) | 0);  /* check that DEVMEM_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 1162691661U))
    n |= 2;
  return n;
}

static int _cffi_const_DEVPTS_SUPER_MAGIC(unsigned long long *o)
{
  int n = (DEVPTS_SUPER_MAGIC) <= 0;
  *o = (unsigned long long)((DEVPTS_SUPER_MAGIC) | 0);  /* check that DEVPTS_SUPER_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 7377U))
    n |= 2;
  return n;
}

static int _cffi_const_DMA_BUF_MAGIC(unsigned long long *o)
{
  int n = (DMA_BUF_MAGIC) <= 0;
  *o = (unsigned long long)((DMA_BUF_MAGIC) | 0);  /* check that DMA_BUF_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 1145913666U))
    n |= 2;
  return n;
}

static int _cffi_const_ECRYPTFS_SUPER_MAGIC(unsigned long long *o)
{
  int n = (ECRYPTFS_SUPER_MAGIC) <= 0;
  *o = (unsigned long long)((ECRYPTFS_SUPER_MAGIC) | 0);  /* check that ECRYPTFS_SUPER_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 61791U))
    n |= 2;
  return n;
}

static int _cffi_const_EFIVARFS_MAGIC(unsigned long long *o)
{
  int n = (EFIVARFS_MAGIC) <= 0;
  *o = (unsigned long long)((EFIVARFS_MAGIC) | 0);  /* check that EFIVARFS_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 3730735588U))
    n |= 2;
  return n;
}

static int _cffi_const_EFS_SUPER_MAGIC(unsigned long long *o)
{
  int n = (EFS_SUPER_MAGIC) <= 0;
  *o = (unsigned long long)((EFS_SUPER_MAGIC) | 0);  /* check that EFS_SUPER_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 4278867U))
    n |= 2;
  return n;
}

static int _cffi_const_EROFS_SUPER_MAGIC_V1(unsigned long long *o)
{
  int n = (EROFS_SUPER_MAGIC_V1) <= 0;
  *o = (unsigned long long)((EROFS_SUPER_MAGIC_V1) | 0);  /* check that EROFS_SUPER_MAGIC_V1 is an integer */
  if (!_cffi_check_int(*o, n, 3774210530U))
    n |= 2;
  return n;
}

static int _cffi_const_EXT2_SUPER_MAGIC(unsigned long long *o)
{
  int n = (EXT2_SUPER_MAGIC) <= 0;
  *o = (unsigned long long)((EXT2_SUPER_MAGIC) | 0);  /* check that EXT2_SUPER_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 61267U))
    n |= 2;
  return n;
}

static int _cffi_const_EXT3_SUPER_MAGIC(unsigned long long *o)
{
  int n = (EXT3_SUPER_MAGIC) <= 0;
  *o = (unsigned long long)((EXT3_SUPER_MAGIC) | 0);  /* check that EXT3_SUPER_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 61267U))
    n |= 2;
  return n;
}

static int _cffi_const_EXT4_SUPER_MAGIC(unsigned long long *o)
{
  int n = (EXT4_SUPER_MAGIC) <= 0;
  *o = (unsigned long long)((EXT4_SUPER_MAGIC) | 0);  /* check that EXT4_SUPER_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 61267U))
    n |= 2;
  return n;
}

static int _cffi_const_F2FS_SUPER_MAGIC(unsigned long long *o)
{
  int n = (F2FS_SUPER_MAGIC) <= 0;
  *o = (unsigned long long)((F2FS_SUPER_MAGIC) | 0);  /* check that F2FS_SUPER_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 4076150800U))
    n |= 2;
  return n;
}

static int _cffi_const_FUTEXFS_SUPER_MAGIC(unsigned long long *o)
{
  int n = (FUTEXFS_SUPER_MAGIC) <= 0;
  *o = (unsigned long long)((FUTEXFS_SUPER_MAGIC) | 0);  /* check that FUTEXFS_SUPER_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 195894762U))
    n |= 2;
  return n;
}

static int _cffi_const_HOSTFS_SUPER_MAGIC(unsigned long long *o)
{
  int n = (HOSTFS_SUPER_MAGIC) <= 0;
  *o = (unsigned long long)((HOSTFS_SUPER_MAGIC) | 0);  /* check that HOSTFS_SUPER_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 12648430U))
    n |= 2;
  return n;
}

static int _cffi_const_HPFS_SUPER_MAGIC(unsigned long long *o)
{
  int n = (HPFS_SUPER_MAGIC) <= 0;
  *o = (unsigned long long)((HPFS_SUPER_MAGIC) | 0);  /* check that HPFS_SUPER_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 4187351113U))
    n |= 2;
  return n;
}

static int _cffi_const_HUGETLBFS_MAGIC(unsigned long long *o)
{
  int n = (HUGETLBFS_MAGIC) <= 0;
  *o = (unsigned long long)((HUGETLBFS_MAGIC) | 0);  /* check that HUGETLBFS_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 2508478710U))
    n |= 2;
  return n;
}

static int _cffi_const_ISOFS_SUPER_MAGIC(unsigned long long *o)
{
  int n = (ISOFS_SUPER_MAGIC) <= 0;
  *o = (unsigned long long)((ISOFS_SUPER_MAGIC) | 0);  /* check that ISOFS_SUPER_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 38496U))
    n |= 2;
  return n;
}

static int _cffi_const_JFFS2_SUPER_MAGIC(unsigned long long *o)
{
  int n = (JFFS2_SUPER_MAGIC) <= 0;
  *o = (unsigned long long)((JFFS2_SUPER_MAGIC) | 0);  /* check that JFFS2_SUPER_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 29366U))
    n |= 2;
  return n;
}

static int _cffi_const_MINIX2_SUPER_MAGIC(unsigned long long *o)
{
  int n = (MINIX2_SUPER_MAGIC) <= 0;
  *o = (unsigned long long)((MINIX2_SUPER_MAGIC) | 0);  /* check that MINIX2_SUPER_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 9320U))
    n |= 2;
  return n;
}

static int _cffi_const_MINIX2_SUPER_MAGIC2(unsigned long long *o)
{
  int n = (MINIX2_SUPER_MAGIC2) <= 0;
  *o = (unsigned long long)((MINIX2_SUPER_MAGIC2) | 0);  /* check that MINIX2_SUPER_MAGIC2 is an integer */
  if (!_cffi_check_int(*o, n, 9336U))
    n |= 2;
  return n;
}

static int _cffi_const_MINIX3_SUPER_MAGIC(unsigned long long *o)
{
  int n = (MINIX3_SUPER_MAGIC) <= 0;
  *o = (unsigned long long)((MINIX3_SUPER_MAGIC) | 0);  /* check that MINIX3_SUPER_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 19802U))
    n |= 2;
  return n;
}

static int _cffi_const_MINIX_SUPER_MAGIC(unsigned long long *o)
{
  int n = (MINIX_SUPER_MAGIC) <= 0;
  *o = (unsigned long long)((MINIX_SUPER_MAGIC) | 0);  /* check that MINIX_SUPER_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 4991U))
    n |= 2;
  return n;
}

static int _cffi_const_MINIX_SUPER_MAGIC2(unsigned long long *o)
{
  int n = (MINIX_SUPER_MAGIC2) <= 0;
  *o = (unsigned long long)((MINIX_SUPER_MAGIC2) | 0);  /* check that MINIX_SUPER_MAGIC2 is an integer */
  if (!_cffi_check_int(*o, n, 5007U))
    n |= 2;
  return n;
}

static int _cffi_const_MSDOS_SUPER_MAGIC(unsigned long long *o)
{
  int n = (MSDOS_SUPER_MAGIC) <= 0;
  *o = (unsigned long long)((MSDOS_SUPER_MAGIC) | 0);  /* check that MSDOS_SUPER_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 19780U))
    n |= 2;
  return n;
}

static int _cffi_const_MTD_INODE_FS_MAGIC(unsigned long long *o)
{
  int n = (MTD_INODE_FS_MAGIC) <= 0;
  *o = (unsigned long long)((MTD_INODE_FS_MAGIC) | 0);  /* check that MTD_INODE_FS_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 288389204U))
    n |= 2;
  return n;
}

static int _cffi_const_NCP_SUPER_MAGIC(unsigned long long *o)
{
  int n = (NCP_SUPER_MAGIC) <= 0;
  *o = (unsigned long long)((NCP_SUPER_MAGIC) | 0);  /* check that NCP_SUPER_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 22092U))
    n |= 2;
  return n;
}

static int _cffi_const_NFS_SUPER_MAGIC(unsigned long long *o)
{
  int n = (NFS_SUPER_MAGIC) <= 0;
  *o = (unsigned long long)((NFS_SUPER_MAGIC) | 0);  /* check that NFS_SUPER_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 26985U))
    n |= 2;
  return n;
}

static int _cffi_const_NILFS_SUPER_MAGIC(unsigned long long *o)
{
  int n = (NILFS_SUPER_MAGIC) <= 0;
  *o = (unsigned long long)((NILFS_SUPER_MAGIC) | 0);  /* check that NILFS_SUPER_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 13364U))
    n |= 2;
  return n;
}

static int _cffi_const_NSFS_MAGIC(unsigned long long *o)
{
  int n = (NSFS_MAGIC) <= 0;
  *o = (unsigned long long)((NSFS_MAGIC) | 0);  /* check that NSFS_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 1853056627U))
    n |= 2;
  return n;
}

static int _cffi_const_OCFS2_SUPER_MAGIC(unsigned long long *o)
{
  int n = (OCFS2_SUPER_MAGIC) <= 0;
  *o = (unsigned long long)((OCFS2_SUPER_MAGIC) | 0);  /* check that OCFS2_SUPER_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 1952539503U))
    n |= 2;
  return n;
}

static int _cffi_const_OPENPROM_SUPER_MAGIC(unsigned long long *o)
{
  int n = (OPENPROM_SUPER_MAGIC) <= 0;
  *o = (unsigned long long)((OPENPROM_SUPER_MAGIC) | 0);  /* check that OPENPROM_SUPER_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 40865U))
    n |= 2;
  return n;
}

static int _cffi_const_OVERLAYFS_SUPER_MAGIC(unsigned long long *o)
{
  int n = (OVERLAYFS_SUPER_MAGIC) <= 0;
  *o = (unsigned long long)((OVERLAYFS_SUPER_MAGIC) | 0);  /* check that OVERLAYFS_SUPER_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 2035054128U))
    n |= 2;
  return n;
}

static int _cffi_const_PIPEFS_MAGIC(unsigned long long *o)
{
  int n = (PIPEFS_MAGIC) <= 0;
  *o = (unsigned long long)((PIPEFS_MAGIC) | 0);  /* check that PIPEFS_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 1346981957U))
    n |= 2;
  return n;
}

static int _cffi_const_PPC_CMM_MAGIC(unsigned long long *o)
{
  int n = (PPC_CMM_MAGIC) <= 0;
  *o = (unsigned long long)((PPC_CMM_MAGIC) | 0);  /* check that PPC_CMM_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 3344373136U))
    n |= 2;
  return n;
}

static int _cffi_const_PROC_SUPER_MAGIC(unsigned long long *o)
{
  int n = (PROC_SUPER_MAGIC) <= 0;
  *o = (unsigned long long)((PROC_SUPER_MAGIC) | 0);  /* check that PROC_SUPER_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 40864U))
    n |= 2;
  return n;
}

static int _cffi_const_PSTOREFS_MAGIC(unsigned long long *o)
{
  int n = (PSTOREFS_MAGIC) <= 0;
  *o = (unsigned long long)((PSTOREFS_MAGIC) | 0);  /* check that PSTOREFS_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 1634035564U))
    n |= 2;
  return n;
}

static int _cffi_const_QNX4_SUPER_MAGIC(unsigned long long *o)
{
  int n = (QNX4_SUPER_MAGIC) <= 0;
  *o = (unsigned long long)((QNX4_SUPER_MAGIC) | 0);  /* check that QNX4_SUPER_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 47U))
    n |= 2;
  return n;
}

static int _cffi_const_QNX6_SUPER_MAGIC(unsigned long long *o)
{
  int n = (QNX6_SUPER_MAGIC) <= 0;
  *o = (unsigned long long)((QNX6_SUPER_MAGIC) | 0);  /* check that QNX6_SUPER_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 1746473250U))
    n |= 2;
  return n;
}

static int _cffi_const_RAMFS_MAGIC(unsigned long long *o)
{
  int n = (RAMFS_MAGIC) <= 0;
  *o = (unsigned long long)((RAMFS_MAGIC) | 0);  /* check that RAMFS_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 2240043254U))
    n |= 2;
  return n;
}

static int _cffi_const_RDTGROUP_SUPER_MAGIC(unsigned long long *o)
{
  int n = (RDTGROUP_SUPER_MAGIC) <= 0;
  *o = (unsigned long long)((RDTGROUP_SUPER_MAGIC) | 0);  /* check that RDTGROUP_SUPER_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 124082209U))
    n |= 2;
  return n;
}

static int _cffi_const_REISERFS_SUPER_MAGIC(unsigned long long *o)
{
  int n = (REISERFS_SUPER_MAGIC) <= 0;
  *o = (unsigned long long)((REISERFS_SUPER_MAGIC) | 0);  /* check that REISERFS_SUPER_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 1382369651U))
    n |= 2;
  return n;
}

static int _cffi_const_SECURITYFS_MAGIC(unsigned long long *o)
{
  int n = (SECURITYFS_MAGIC) <= 0;
  *o = (unsigned long long)((SECURITYFS_MAGIC) | 0);  /* check that SECURITYFS_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 1935894131U))
    n |= 2;
  return n;
}

static int _cffi_const_SELINUX_MAGIC(unsigned long long *o)
{
  int n = (SELINUX_MAGIC) <= 0;
  *o = (unsigned long long)((SELINUX_MAGIC) | 0);  /* check that SELINUX_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 4185718668U))
    n |= 2;
  return n;
}

static int _cffi_const_SHIFTFS_MAGIC(unsigned long long *o)
{
  int n = (SHIFTFS_MAGIC) <= 0;
  *o = (unsigned long long)((SHIFTFS_MAGIC) | 0);  /* check that SHIFTFS_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 1785031266U))
    n |= 2;
  return n;
}

static int _cffi_const_SMACK_MAGIC(unsigned long long *o)
{
  int n = (SMACK_MAGIC) <= 0;
  *o = (unsigned long long)((SMACK_MAGIC) | 0);  /* check that SMACK_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 1128357203U))
    n |= 2;
  return n;
}

static int _cffi_const_SMB_SUPER_MAGIC(unsigned long long *o)
{
  int n = (SMB_SUPER_MAGIC) <= 0;
  *o = (unsigned long long)((SMB_SUPER_MAGIC) | 0);  /* check that SMB_SUPER_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 20859U))
    n |= 2;
  return n;
}

static int _cffi_const_SOCKFS_MAGIC(unsigned long long *o)
{
  int n = (SOCKFS_MAGIC) <= 0;
  *o = (unsigned long long)((SOCKFS_MAGIC) | 0);  /* check that SOCKFS_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 1397703499U))
    n |= 2;
  return n;
}

static int _cffi_const_SQUASHFS_MAGIC(unsigned long long *o)
{
  int n = (SQUASHFS_MAGIC) <= 0;
  *o = (unsigned long long)((SQUASHFS_MAGIC) | 0);  /* check that SQUASHFS_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 1936814952U))
    n |= 2;
  return n;
}

static int _cffi_const_STACK_END_MAGIC(unsigned long long *o)
{
  int n = (STACK_END_MAGIC) <= 0;
  *o = (unsigned long long)((STACK_END_MAGIC) | 0);  /* check that STACK_END_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 1470918301U))
    n |= 2;
  return n;
}

static int _cffi_const_SYSFS_MAGIC(unsigned long long *o)
{
  int n = (SYSFS_MAGIC) <= 0;
  *o = (unsigned long long)((SYSFS_MAGIC) | 0);  /* check that SYSFS_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 1650812274U))
    n |= 2;
  return n;
}

static int _cffi_const_TMPFS_MAGIC(unsigned long long *o)
{
  int n = (TMPFS_MAGIC) <= 0;
  *o = (unsigned long long)((TMPFS_MAGIC) | 0);  /* check that TMPFS_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 16914836U))
    n |= 2;
  return n;
}

static int _cffi_const_TRACEFS_MAGIC(unsigned long long *o)
{
  int n = (TRACEFS_MAGIC) <= 0;
  *o = (unsigned long long)((TRACEFS_MAGIC) | 0);  /* check that TRACEFS_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 1953653091U))
    n |= 2;
  return n;
}

static int _cffi_const_UDF_SUPER_MAGIC(unsigned long long *o)
{
  int n = (UDF_SUPER_MAGIC) <= 0;
  *o = (unsigned long long)((UDF_SUPER_MAGIC) | 0);  /* check that UDF_SUPER_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 352400198U))
    n |= 2;
  return n;
}

static int _cffi_const_USBDEVICE_SUPER_MAGIC(unsigned long long *o)
{
  int n = (USBDEVICE_SUPER_MAGIC) <= 0;
  *o = (unsigned long long)((USBDEVICE_SUPER_MAGIC) | 0);  /* check that USBDEVICE_SUPER_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 40866U))
    n |= 2;
  return n;
}

static int _cffi_const_V9FS_MAGIC(unsigned long long *o)
{
  int n = (V9FS_MAGIC) <= 0;
  *o = (unsigned long long)((V9FS_MAGIC) | 0);  /* check that V9FS_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 16914839U))
    n |= 2;
  return n;
}

static int _cffi_const_XENFS_SUPER_MAGIC(unsigned long long *o)
{
  int n = (XENFS_SUPER_MAGIC) <= 0;
  *o = (unsigned long long)((XENFS_SUPER_MAGIC) | 0);  /* check that XENFS_SUPER_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 2881100148U))
    n |= 2;
  return n;
}

static int _cffi_const_XFS_SUPER_MAGIC(unsigned long long *o)
{
  int n = (XFS_SUPER_MAGIC) <= 0;
  *o = (unsigned long long)((XFS_SUPER_MAGIC) | 0);  /* check that XFS_SUPER_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 1481003842U))
    n |= 2;
  return n;
}

static int _cffi_const_Z3FOLD_MAGIC(unsigned long long *o)
{
  int n = (Z3FOLD_MAGIC) <= 0;
  *o = (unsigned long long)((Z3FOLD_MAGIC) | 0);  /* check that Z3FOLD_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 51U))
    n |= 2;
  return n;
}

static int _cffi_const_ZONEFS_MAGIC(unsigned long long *o)
{
  int n = (ZONEFS_MAGIC) <= 0;
  *o = (unsigned long long)((ZONEFS_MAGIC) | 0);  /* check that ZONEFS_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 1515144787U))
    n |= 2;
  return n;
}

static int _cffi_const_ZSMALLOC_MAGIC(unsigned long long *o)
{
  int n = (ZSMALLOC_MAGIC) <= 0;
  *o = (unsigned long long)((ZSMALLOC_MAGIC) | 0);  /* check that ZSMALLOC_MAGIC is an integer */
  if (!_cffi_check_int(*o, n, 1479104553U))
    n |= 2;
  return n;
}

_CFFI_UNUSED_FN
static void _cffi_checkfld_struct_statfs(struct statfs *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  (void)((p->f_type) | 0);  /* check that 'struct statfs.f_type' is an integer */
  (void)((p->f_bsize) | 0);  /* check that 'struct statfs.f_bsize' is an integer */
  (void)((p->f_blocks) | 0);  /* check that 'struct statfs.f_blocks' is an integer */
  (void)((p->f_bfree) | 0);  /* check that 'struct statfs.f_bfree' is an integer */
  (void)((p->f_bavail) | 0);  /* check that 'struct statfs.f_bavail' is an integer */
  (void)((p->f_files) | 0);  /* check that 'struct statfs.f_files' is an integer */
  (void)((p->f_ffree) | 0);  /* check that 'struct statfs.f_ffree' is an integer */
  { __fsid_t *tmp = &p->f_fsid; (void)tmp; }
  (void)((p->f_namelen) | 0);  /* check that 'struct statfs.f_namelen' is an integer */
  (void)((p->f_frsize) | 0);  /* check that 'struct statfs.f_frsize' is an integer */
  (void)((p->f_flags) | 0);  /* check that 'struct statfs.f_flags' is an integer */
  { long(*tmp)[4] = &p->f_spare; (void)tmp; }
}
struct _cffi_align_struct_statfs { char x; struct statfs y; };

static const struct _cffi_global_s _cffi_globals[] = {
  { "AAFS_MAGIC", (void *)_cffi_const_AAFS_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "ADFS_SUPER_MAGIC", (void *)_cffi_const_ADFS_SUPER_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "AFFS_SUPER_MAGIC", (void *)_cffi_const_AFFS_SUPER_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "AFS_FS_MAGIC", (void *)_cffi_const_AFS_FS_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "AFS_SUPER_MAGIC", (void *)_cffi_const_AFS_SUPER_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "ANON_INODE_FS_MAGIC", (void *)_cffi_const_ANON_INODE_FS_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "AUTOFS_SUPER_MAGIC", (void *)_cffi_const_AUTOFS_SUPER_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "BALLOON_KVM_MAGIC", (void *)_cffi_const_BALLOON_KVM_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "BDEVFS_MAGIC", (void *)_cffi_const_BDEVFS_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "BINDERFS_SUPER_MAGIC", (void *)_cffi_const_BINDERFS_SUPER_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "BINFMTFS_MAGIC", (void *)_cffi_const_BINFMTFS_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "BPF_FS_MAGIC", (void *)_cffi_const_BPF_FS_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "BTRFS_SUPER_MAGIC", (void *)_cffi_const_BTRFS_SUPER_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "BTRFS_TEST_MAGIC", (void *)_cffi_const_BTRFS_TEST_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "CGROUP2_SUPER_MAGIC", (void *)_cffi_const_CGROUP2_SUPER_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "CGROUP_SUPER_MAGIC", (void *)_cffi_const_CGROUP_SUPER_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "CODA_SUPER_MAGIC", (void *)_cffi_const_CODA_SUPER_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "CRAMFS_MAGIC", (void *)_cffi_const_CRAMFS_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "CRAMFS_MAGIC_WEND", (void *)_cffi_const_CRAMFS_MAGIC_WEND, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "DAXFS_MAGIC", (void *)_cffi_const_DAXFS_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "DEBUGFS_MAGIC", (void *)_cffi_const_DEBUGFS_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "DEVMEM_MAGIC", (void *)_cffi_const_DEVMEM_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "DEVPTS_SUPER_MAGIC", (void *)_cffi_const_DEVPTS_SUPER_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "DMA_BUF_MAGIC", (void *)_cffi_const_DMA_BUF_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "ECRYPTFS_SUPER_MAGIC", (void *)_cffi_const_ECRYPTFS_SUPER_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "EFIVARFS_MAGIC", (void *)_cffi_const_EFIVARFS_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "EFS_SUPER_MAGIC", (void *)_cffi_const_EFS_SUPER_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "EROFS_SUPER_MAGIC_V1", (void *)_cffi_const_EROFS_SUPER_MAGIC_V1, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "EXT2_SUPER_MAGIC", (void *)_cffi_const_EXT2_SUPER_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "EXT3_SUPER_MAGIC", (void *)_cffi_const_EXT3_SUPER_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "EXT4_SUPER_MAGIC", (void *)_cffi_const_EXT4_SUPER_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "F2FS_SUPER_MAGIC", (void *)_cffi_const_F2FS_SUPER_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "FUTEXFS_SUPER_MAGIC", (void *)_cffi_const_FUTEXFS_SUPER_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "HOSTFS_SUPER_MAGIC", (void *)_cffi_const_HOSTFS_SUPER_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "HPFS_SUPER_MAGIC", (void *)_cffi_const_HPFS_SUPER_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "HUGETLBFS_MAGIC", (void *)_cffi_const_HUGETLBFS_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "ISOFS_SUPER_MAGIC", (void *)_cffi_const_ISOFS_SUPER_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "JFFS2_SUPER_MAGIC", (void *)_cffi_const_JFFS2_SUPER_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "MINIX2_SUPER_MAGIC", (void *)_cffi_const_MINIX2_SUPER_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "MINIX2_SUPER_MAGIC2", (void *)_cffi_const_MINIX2_SUPER_MAGIC2, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "MINIX3_SUPER_MAGIC", (void *)_cffi_const_MINIX3_SUPER_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "MINIX_SUPER_MAGIC", (void *)_cffi_const_MINIX_SUPER_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "MINIX_SUPER_MAGIC2", (void *)_cffi_const_MINIX_SUPER_MAGIC2, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "MSDOS_SUPER_MAGIC", (void *)_cffi_const_MSDOS_SUPER_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "MTD_INODE_FS_MAGIC", (void *)_cffi_const_MTD_INODE_FS_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "NCP_SUPER_MAGIC", (void *)_cffi_const_NCP_SUPER_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "NFS_SUPER_MAGIC", (void *)_cffi_const_NFS_SUPER_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "NILFS_SUPER_MAGIC", (void *)_cffi_const_NILFS_SUPER_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "NSFS_MAGIC", (void *)_cffi_const_NSFS_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "OCFS2_SUPER_MAGIC", (void *)_cffi_const_OCFS2_SUPER_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "OPENPROM_SUPER_MAGIC", (void *)_cffi_const_OPENPROM_SUPER_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "OVERLAYFS_SUPER_MAGIC", (void *)_cffi_const_OVERLAYFS_SUPER_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "PIPEFS_MAGIC", (void *)_cffi_const_PIPEFS_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "PPC_CMM_MAGIC", (void *)_cffi_const_PPC_CMM_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "PROC_SUPER_MAGIC", (void *)_cffi_const_PROC_SUPER_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "PSTOREFS_MAGIC", (void *)_cffi_const_PSTOREFS_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "QNX4_SUPER_MAGIC", (void *)_cffi_const_QNX4_SUPER_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "QNX6_SUPER_MAGIC", (void *)_cffi_const_QNX6_SUPER_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "RAMFS_MAGIC", (void *)_cffi_const_RAMFS_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "RDTGROUP_SUPER_MAGIC", (void *)_cffi_const_RDTGROUP_SUPER_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "REISERFS_SUPER_MAGIC", (void *)_cffi_const_REISERFS_SUPER_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "SECURITYFS_MAGIC", (void *)_cffi_const_SECURITYFS_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "SELINUX_MAGIC", (void *)_cffi_const_SELINUX_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "SHIFTFS_MAGIC", (void *)_cffi_const_SHIFTFS_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "SMACK_MAGIC", (void *)_cffi_const_SMACK_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "SMB_SUPER_MAGIC", (void *)_cffi_const_SMB_SUPER_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "SOCKFS_MAGIC", (void *)_cffi_const_SOCKFS_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "SQUASHFS_MAGIC", (void *)_cffi_const_SQUASHFS_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "STACK_END_MAGIC", (void *)_cffi_const_STACK_END_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "SYSFS_MAGIC", (void *)_cffi_const_SYSFS_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "TMPFS_MAGIC", (void *)_cffi_const_TMPFS_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "TRACEFS_MAGIC", (void *)_cffi_const_TRACEFS_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "UDF_SUPER_MAGIC", (void *)_cffi_const_UDF_SUPER_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "USBDEVICE_SUPER_MAGIC", (void *)_cffi_const_USBDEVICE_SUPER_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "V9FS_MAGIC", (void *)_cffi_const_V9FS_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "XENFS_SUPER_MAGIC", (void *)_cffi_const_XENFS_SUPER_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "XFS_SUPER_MAGIC", (void *)_cffi_const_XFS_SUPER_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "Z3FOLD_MAGIC", (void *)_cffi_const_Z3FOLD_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "ZONEFS_MAGIC", (void *)_cffi_const_ZONEFS_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "ZSMALLOC_MAGIC", (void *)_cffi_const_ZSMALLOC_MAGIC, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "statfs", (void *)_cffi_f_statfs, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 0), (void *)_cffi_d_statfs },
};

static const struct _cffi_field_s _cffi_fields[] = {
  { "__val", offsetof(__fsid_t, __val),
             sizeof(((__fsid_t *)0)->__val),
             _CFFI_OP(_CFFI_OP_NOOP, 7) },
  { "f_type", offsetof(struct statfs, f_type),
              sizeof(((struct statfs *)0)->f_type),
              _CFFI_OP(_CFFI_OP_NOOP, 9) },
  { "f_bsize", offsetof(struct statfs, f_bsize),
               sizeof(((struct statfs *)0)->f_bsize),
               _CFFI_OP(_CFFI_OP_NOOP, 9) },
  { "f_blocks", offsetof(struct statfs, f_blocks),
                sizeof(((struct statfs *)0)->f_blocks),
                _CFFI_OP(_CFFI_OP_NOOP, 13) },
  { "f_bfree", offsetof(struct statfs, f_bfree),
               sizeof(((struct statfs *)0)->f_bfree),
               _CFFI_OP(_CFFI_OP_NOOP, 13) },
  { "f_bavail", offsetof(struct statfs, f_bavail),
                sizeof(((struct statfs *)0)->f_bavail),
                _CFFI_OP(_CFFI_OP_NOOP, 13) },
  { "f_files", offsetof(struct statfs, f_files),
               sizeof(((struct statfs *)0)->f_files),
               _CFFI_OP(_CFFI_OP_NOOP, 13) },
  { "f_ffree", offsetof(struct statfs, f_ffree),
               sizeof(((struct statfs *)0)->f_ffree),
               _CFFI_OP(_CFFI_OP_NOOP, 13) },
  { "f_fsid", offsetof(struct statfs, f_fsid),
              sizeof(((struct statfs *)0)->f_fsid),
              _CFFI_OP(_CFFI_OP_NOOP, 4) },
  { "f_namelen", offsetof(struct statfs, f_namelen),
                 sizeof(((struct statfs *)0)->f_namelen),
                 _CFFI_OP(_CFFI_OP_NOOP, 9) },
  { "f_frsize", offsetof(struct statfs, f_frsize),
                sizeof(((struct statfs *)0)->f_frsize),
                _CFFI_OP(_CFFI_OP_NOOP, 9) },
  { "f_flags", offsetof(struct statfs, f_flags),
               sizeof(((struct statfs *)0)->f_flags),
               _CFFI_OP(_CFFI_OP_NOOP, 9) },
  { "f_spare", offsetof(struct statfs, f_spare),
               sizeof(((struct statfs *)0)->f_spare),
               _CFFI_OP(_CFFI_OP_NOOP, 10) },
};

static const struct _cffi_struct_union_s _cffi_struct_unions[] = {
  { "$__fsid_t", 4, _CFFI_F_CHECK_FIELDS,
    sizeof(__fsid_t), offsetof(struct _cffi_align_typedef___fsid_t, y), 0, 1 },
  { "statfs", 12, _CFFI_F_CHECK_FIELDS,
    sizeof(struct statfs), offsetof(struct _cffi_align_struct_statfs, y), 1, 12 },
};

static const struct _cffi_typename_s _cffi_typenames[] = {
  { "__fsblkcnt_t", 13 },
  { "__fsfilcnt_t", 13 },
  { "__fsid_t", 4 },
  { "__fsword_t", 9 },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  _cffi_fields,
  _cffi_struct_unions,
  NULL,  /* no enums */
  _cffi_typenames,
  81,  /* num_globals */
  2,  /* num_struct_unions */
  0,  /* num_enums */
  4,  /* num_typenames */
  NULL,  /* no includes */
  14,  /* num_types */
  0,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit_pystatfs(const void *p[])
{
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
#if PY_MAJOR_VERSION >= 3
    return NULL;
#endif
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
#  if PY_MAJOR_VERSION >= 3
     PyInit_pystatfs(void) { return NULL; }
#  else
     initpystatfs(void) { }
#  endif
#  endif
#elif PY_MAJOR_VERSION >= 3
PyMODINIT_FUNC
PyInit_pystatfs(void)
{
  return _cffi_init("pystatfs", 0x2601, &_cffi_type_context);
}
#else
PyMODINIT_FUNC
initpystatfs(void)
{
  _cffi_init("pystatfs", 0x2601, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
